import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-4xl mx-auto`}
      >
        <nav>
          <Navbar />
        </nav>
        <main className="min-h-[700px] place-content-center place-items-center">
          {children}
        </main>
        <footer>
          <h1 className="text-sm text-center">&copy; Awesome Next.js Project 2025</h1>
        </footer>
      </body>
    </html>
  );
}
